project:
  type: website
  output-dir: docs

website:
  title: "Project Website with Art"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Data Viz"
        menu: 
         - text: "CDC Data"
           href: CDC_Data.qmd
         - text: "Water Insecurity"
           href: Water_Insecurity.html
      - text: "Text Analysis"
        href: Text_analysis.qmd
      - text: "Probability"
        href: Probability.qmd
      - text: "Ethics"
        href: Ethics.qmd
      - text: "SQL"
        href: SQL.qmd
      - text: "Presentation"
        href: Presentation.qmd

format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

